### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by MartinMuzatko** [Aerobird98/codemirror-one-dark-theme#1]
Hello! I would love to use this for my OS project. Can you make it a NPM package please? :)

**Comment by Aerobird98** [comment]
Hello, im glad to hear, that you like it.
Im realy busy in the moment, but yes, i plan to make it available through NPM.

**Comment by Aerobird98** [comment]
I made it available through [NPM](https://www.npmjs.com/package/codemirror-one-dark-theme).
Hope you make good use of it! ;)

**Comment by MartinMuzatko** [comment]
Hello! Thank you a lot! It will find its use here: https://martinmuzatko.github.io/flexproperties
Finally I can mange to have prismjs and codemirror look alike.

Thank you for your time :)

**Comment by Sjoerd** [comment]
How do I import/require it? (I've installed it with NPM)
